version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "local_postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=trader
      - POSTGRES_PASSWORD=trader
      - POSTGRES_DB=ticksdb
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
